services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    ports:
      - '3000:3000'
    env_file:
      - ./apps/reservations/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/my-sleepr
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    ports:
      - '3001:3001'
    env_file:
      - ./apps/auth/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/my-sleepr
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/my-sleepr
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    image: mongo
